import Config

config :prism,
  discord_base_url: "http://localhost:4002",
  finch_pool_count: 10,
  finch_protocols: [:http1],
  finch_receive_timeout_ms: 30_000,
  finch_pool_timeout_ms: 10_000,
  finch_idle_timeout_ms: 60_000,
  finch_keepalive_ms: 30_000,
  backpressure_enabled: true,
  backpressure_max_backoff_ms: 600_000,
  backpressure_min_cooldown_ms: 60_000,
  invalid_request_window_ms: 600_000,
  invalid_request_backpressure_threshold: 9_500,
  invalid_request_critical_threshold: 10_000,
  bucket_hash_ttl_seconds: 3600,
  max_async_batches: 10,
  batch_max_concurrency: 5,
  callback_include_parent_message_id: false,
  reply_index_enabled: false,
  reply_index_prefix: "p:d",
  reply_index_ttl_seconds: 604_800,
  dead_message_cache_enabled: true,
  key_expansion_enabled: true,
  cancel_checker_enabled: true,
  stream_trimmer_enabled: true,
  redis_opts: [host: "localhost", port: 6379],
  redix_pool_size: 5,
  show_test_logs: System.get_env("PRISM_SHOW_LOGS") == "1"
